jwt:
  secret: abcdefghabcdefghabcdefghabcdefghabcdefghabcdefefeq
member:
  url: ${MEMBER_URL}
  port: ${MEMBER_PORT}
performance:
  url: ${PERFORMANCE_URL}
  port: ${PERFORMANCE_PORT}
reservation:
  url: ${RESERVATION_URL}
  port: ${RESERVATION_PORT}
spring:
  redis:
    host: ${REDIS_URL}
    port: ${REDIS_PORT}
server:
  port: ${SERVER_PORT}